### ISSUE TITLE
pfSense template

### ISSUE THREAD

**Issue by elimpnick** [freenas/vm-templates#1]
Any chance a pfSense template could be created?  A lot of people have been waiting on a dual pfSense/FreeNAS system and instead of using a traditional Hypervisor, being able to load a pfSense template inside FreeNAS would be great!

**Comment by svkamp** [comment]
Id be curious how you envision that being able to work with pfsense as a guest

**Comment by elimpnick** [comment]
I have a mini ITX 8-core Xeon-D board with 4x 1GB LAN ports.  I would dedicate 2 of the LAN ports to the host (FreeNAS) which are etherchannel'd on the LAN switch. For the pfSense VM I would bridge the last remaining 2 LAN ports and pfSense would be the firewall on the WAN side to the Internet.

Anyway, a lot of people (including myself) have successfully run both on the same hardware with ESXi or Xen, but it would be great if FreeNAS 10 had a template to support such configuration.

**Comment by shangteus** [comment]
So we've added pfSense template. Feel free to install and configure networking to your needs.

**Comment by elimpnick** [comment]
Cool thanks!
