### ISSUE TITLE
Info on the settings/steps used in these templates?

### ISSUE THREAD

**Issue by justinclift** [freenas/vm-templates#2]
This templates repo looks like a good idea.

As a thought when looking at the current OpenBSD template, it's presently for OpenBSD 5.9 (now superseded) + using a binary blob from the iXSystems website:

  * https://github.com/freenas/vm-templates/blob/ced8b044e5e35b2a17b40c22061a27ad6ccf5a55/openbsd-5.9/template.json

Is the general idea (down the track), to have the steps/build-process used to generate these binary blobs documented or put in git somewhere? :smile:

Maybe for use by a config management system like Ansible or Salt, so they can be replicated/rebuilt without much hassle?

**Comment by jordanhubbard** [comment]
1. The binary blob is just a URL - it can point anywhere (we just thought it most user-friendly to host the blobs on our CDN).  A template could obviously refer to a binary blob elsewhere and that would be just fine, assuming that "elsewhere" didn't disappear again.

2. Yep, it's documented - I put this together a few months ago: https://github.com/freenas/vm-templates/blob/master/README.md  - it's at the very base of the vm-templates repo so github should have shown it to you.

3. We're also going to make it easy to "publish" a VM; we had this in place pre-BETA (using IPFS as the publishing mechanism) but we couldn't make it reliable enough and punted for now.  We'll bring it back soon!

**Comment by justinclift** [comment]
Ahhh, guess I worded this wrongly. Sorry. :smile:

The README.md file does show how to add new template definitions, and does it pretty well.

The question I'm trying to ask is slightly different.  It's not "How to add/update a template?", it's more "That OpenBSD binary .iso there... it's not an official OpenBSD download.  What are the exact steps that were used to build it, so people can verify it?".  More a traceability/prove-its-known-good thing.

**Comment by jordanhubbard** [comment]
It's just a frozen, compressed install.  It's not official in any way, nor is there a "recipe" for it because this stuff isn't automated yet.  You just create a VM on your box using an ISO image and a suitably pre-sized disk, then you stop the VM and gzip its data disk (zvol, in /dev).   However, since OpenBSD users tend to be kind of paranoid about where their bits come from, I get that this was probably a bad template target and have now removed it - problem solved! 🎉

**Comment by justinclift** [comment]
Heh Heh Heh

Yeah, I guess that's one way to do it. :wink:
