### ISSUE TITLE
Ubuntu VM only has a 12GB drive and this can't be over-ridden by settings

### ISSUE THREAD

**Issue by animeai** [freenas/vm-templates#7]
On the Ubuntu Server-16 VM, the main drive is 12GB fixed size, after installing a couple of things with apt-get (dist-upgrade, python-dev and go-lang) we are at 100% full... There is no obvious way to increase the drive size from 12GB and unless I start moving and symlinking all major directories to NAS storage (something I'd rather not do!) the system is more or less useless. Setting the device "OS" to 32GB instead of 16GB (12GB drive and 4GB swap) during creation made no difference.

**Comment by jceel** [comment]
Changing size of the disk on FreeNAS side is not enough - please refer to the Ubuntu manuals on how to enlarge a boot device.
